from __future__ import annotations

PAGE_STYLE = r"""
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,sans-serif;--bg:#0b1220;--card:#111c2f;--line:#263449;--field:#07101f;--text:#e5e7eb;--muted:#94a3b8;--primary:#2563eb;--success:#047857;--danger:#b91c1c}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text)}
button,input,select,textarea{font:inherit}button{border:0;border-radius:.75rem;background:var(--primary);color:#fff;font-weight:800;cursor:pointer;min-height:2.8rem;padding:.72rem 1rem}button.secondary{background:#334155}button.success{background:var(--success)}button.danger{background:var(--danger)}button:disabled{opacity:.48;cursor:not-allowed}
input,select,textarea{width:100%;border:1px solid #334155;border-radius:.75rem;background:var(--field);color:var(--text);padding:.78rem}textarea{min-height:8.5rem;resize:vertical;line-height:1.45}label{display:block;margin:.55rem 0 .3rem;font-size:.88rem;font-weight:750;color:#cbd5e1}
header{position:sticky;top:0;z-index:10;padding:calc(.68rem + env(safe-area-inset-top)) 1rem .68rem;background:rgba(15,23,42,.96);border-bottom:1px solid var(--line);backdrop-filter:blur(12px)}
.header-row{max-width:820px;margin:auto;display:flex;align-items:center;justify-content:space-between;gap:.8rem}.brand strong{font-size:1.02rem}.brand small{display:block;color:var(--muted);margin-top:.12rem}.header-meta{display:flex;align-items:center;gap:.45rem;flex-wrap:wrap;justify-content:flex-end}
main{max-width:820px;margin:auto;padding:1rem 1rem calc(2rem + env(safe-area-inset-bottom));display:grid;gap:.85rem}.hero{padding:.3rem .15rem .1rem}.hero h1{font-size:clamp(1.45rem,5vw,2rem);margin:.1rem 0 .35rem}.hero p{margin:0;color:#b9c6d8;line-height:1.5}
.card{background:var(--card);border:1px solid var(--line);border-radius:1rem;padding:1rem;box-shadow:0 12px 30px rgba(0,0,0,.14)}.step-head{display:grid;grid-template-columns:2.2rem 1fr;gap:.7rem;align-items:start;margin-bottom:.8rem}.step-number{display:grid;place-items:center;width:2.2rem;height:2.2rem;border-radius:50%;background:#1d4ed8;font-weight:900}.step-head h2{font-size:1.04rem;margin:.05rem 0 .15rem}.step-head p{margin:0;color:var(--muted);font-size:.88rem;line-height:1.4}
.actions{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:.55rem;margin-top:.65rem}.provider-actions{display:grid;grid-template-columns:repeat(3,1fr);gap:.55rem;margin-top:.55rem}.provider-actions button{background:#243247}.provider-actions button:first-child{background:#126b56}
.status-strip{display:flex;align-items:center;justify-content:space-between;gap:.7rem;flex-wrap:wrap}.project-name{font-weight:850}.muted{color:var(--muted);font-size:.87rem}.badge{display:inline-block;padding:.22rem .52rem;border-radius:999px;background:#1e3a5f;color:#bfdbfe;font-size:.75rem;font-weight:800}.feedback{display:none;margin-top:.7rem;padding:.7rem .8rem;border-radius:.7rem;background:#0c1729;border:1px solid var(--line);white-space:pre-wrap;overflow-wrap:anywhere}.feedback.visible{display:block}.feedback.ok{border-color:#166534;color:#bbf7d0}.feedback.error{border-color:#991b1b;color:#fecaca}
details{margin-top:.75rem;border-top:1px solid var(--line);padding-top:.7rem}summary{cursor:pointer;color:#cbd5e1;font-weight:800}.details-body{padding-top:.6rem}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.65rem}.inline-check{display:flex;align-items:center;gap:.55rem;margin-top:.7rem}.inline-check input{width:auto}.separator{display:flex;align-items:center;gap:.65rem;color:var(--muted);font-size:.8rem;margin:.8rem 0}.separator:before,.separator:after{content:"";height:1px;background:var(--line);flex:1}
.preview{display:none;margin-top:.8rem}.preview.visible{display:block}.change-list{margin:.55rem 0 0;padding-left:1.2rem;color:#cbd5e1}.change-list li{margin:.25rem 0}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:var(--field);border:1px solid var(--line);padding:.8rem;border-radius:.7rem;max-height:26rem;overflow:auto;margin:.7rem 0 0;font-size:.82rem}.compact textarea{min-height:6.2rem}.advanced-card details{margin-top:0;border-top:0;padding-top:0}.advanced-card summary{font-size:.95rem}
#authCard,#appContent{display:none}#busy{position:fixed;inset:0;display:none;place-items:center;background:rgba(2,6,23,.74);z-index:30}#busy div{background:var(--card);border:1px solid #334155;border-radius:1rem;padding:1rem 1.35rem;font-weight:850}.connection-line strong{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;color:#dbeafe}
@media(max-width:640px){main{padding-inline:.7rem}.card{border-radius:.88rem;padding:.85rem}.grid,.provider-actions{grid-template-columns:1fr}.header-row{align-items:flex-start}.connection-line{display:none}}
"""

PAGE_SCRIPT = r"""
const csrf=__CSRF__;
const authKey='bridgai-web-basic-auth';
let currentPlanId=null;
let currentChanges=[];

const byId=id=>document.getElementById(id);
function authorization(){return sessionStorage.getItem(authKey)||''}
function headers(extra={}){const value={...extra};if(authorization())value.Authorization=authorization();return value}
function setBusy(value){byId('busy').style.display=value?'grid':'none'}
function feedback(id,text,type=''){const element=byId(id);element.textContent=text||'';element.className='feedback visible'+(type?' '+type:'')}
function clearFeedback(id){const element=byId(id);element.textContent='';element.className='feedback'}
function projectLabel(path){if(!path)return'Nessun progetto aperto';const parts=path.replace(/\\/g,'/').split('/').filter(Boolean);return parts.at(-1)||path}
async function jsonResponse(response){const data=await response.json().catch(()=>({error:'Risposta server non valida'}));if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data}
async function api(path,body){return jsonResponse(await fetch(path,{method:'POST',headers:headers({'Content-Type':'application/json','X-Local-Bridge-CSRF':csrf}),body:JSON.stringify(body||{})}))}
async function withBusy(action,errorTarget){setBusy(true);try{return await action()}catch(error){feedback(errorTarget,error.message,'error');throw error}finally{setBusy(false)}}

function login(){const username=byId('authUsername').value.trim();const password=byId('authPassword').value;if(!username||!password){feedback('authResult','Inserisci username e password.','error');return}sessionStorage.setItem(authKey,'Basic '+btoa(unescape(encodeURIComponent(username+':'+password))));byId('authPassword').value='';refreshStatus()}
function logout(){sessionStorage.removeItem(authKey);currentPlanId=null;refreshStatus()}
function renderConnection(status){byId('connectionAddress').textContent=status.connection_address||window.location.host}
function renderWorkspacePicker(status){const host=byId('workspacePicker');host.replaceChildren();const items=status.workspaces||[];if(items.length){const label=document.createElement('label');label.htmlFor='workspace';label.textContent='Progetto';const select=document.createElement('select');select.id='workspace';const placeholder=document.createElement('option');placeholder.value='';placeholder.textContent='Seleziona un progetto…';select.appendChild(placeholder);items.forEach(item=>{const option=document.createElement('option');option.value=item.value;option.textContent=item.name+(item.git?' · Git':'');option.selected=item.value===status.workspace;select.appendChild(option)});host.append(label,select);byId('openWorkspaceButton').disabled=false}else{const note=document.createElement('p');note.className='muted';note.textContent=status.workspace?'Il server usa un workspace fisso.':'Configura la root nelle Impostazioni del programma BridgAI e riavvia la Web UI.';host.appendChild(note);byId('openWorkspaceButton').disabled=true}}
function renderProjectSettings(status){byId('currentProject').textContent=projectLabel(status.workspace);byId('workspacePath').textContent=status.workspace||'Nessun workspace selezionato';byId('workspaceRoot').value=status.workspace_root||'';byId('projectManagement').style.display=status.can_manage_projects?'block':'none';byId('projectTools').open=!status.workspace;byId('rootHelp').textContent=status.fixed_workspace?'Il server è limitato al workspace configurato all’avvio.':status.workspace_root?'Ogni cartella diretta della root viene proposta come progetto.':'Configura la root nelle Impostazioni del programma BridgAI e riavvia la Web UI.'}
async function refreshStatus(){try{const status=await jsonResponse(await fetch('/api/status',{headers:headers()}));byId('authCard').style.display='none';byId('appContent').style.display='block';byId('modeBadge').textContent=status.remote_mode?'Remoto protetto':'Locale';renderConnection(status);renderProjectSettings(status);renderWorkspacePicker(status);clearFeedback('authResult')}catch(error){byId('authCard').style.display='block';byId('appContent').style.display='none';byId('modeBadge').textContent='Accesso richiesto';feedback('authResult',error.message,'error')}}
async function setWorkspace(){await withBusy(async()=>{const selector=byId('workspace');if(!selector||!selector.value)throw new Error('Seleziona un progetto.');const data=await api('/api/workspace',{path:selector.value});currentPlanId=null;resetPlan();feedback('projectResult','Progetto aperto: '+projectLabel(data.workspace),'ok');await refreshStatus()},'projectResult').catch(()=>{})}
async function createProject(){const name=byId('newProjectName').value.trim();if(!name||!confirm(`Creare il progetto “${name}”?`))return;await withBusy(async()=>{const data=await api('/api/projects/create',{name,initialize_git:byId('initializeGit').checked,confirm:'CREATE'});byId('newProjectName').value='';feedback('projectResult','Progetto creato e aperto: '+projectLabel(data.workspace),'ok');await refreshStatus()},'projectResult').catch(()=>{})}
async function cloneProject(){const repository=byId('cloneRepository').value.trim();const name=byId('cloneProjectName').value.trim();if(!repository||!confirm(`Clonare questo repository?\n${repository}`))return;await withBusy(async()=>{const data=await api('/api/projects/clone',{repository,name,confirm:'CLONE'});byId('cloneRepository').value='';byId('cloneProjectName').value='';feedback('projectResult','Repository clonato e aperto: '+projectLabel(data.workspace),'ok');await refreshStatus()},'projectResult').catch(()=>{})}

async function copyValue(id){const value=byId(id).value;if(!value)throw new Error('Non c’è ancora nulla da copiare.');try{await navigator.clipboard.writeText(value)}catch(_){const helper=document.createElement('textarea');helper.value=value;helper.setAttribute('readonly','');helper.style.position='fixed';helper.style.opacity='0';document.body.appendChild(helper);helper.select();if(!document.execCommand('copy'))throw new Error('Copia automatica non disponibile. Apri la richiesta e copiala manualmente.');helper.remove()}}
async function generateReport(){await withBusy(async()=>{const task=byId('task').value.trim();if(!task)throw new Error('Descrivi prima cosa vuoi ottenere.');const data=await api('/api/report',{task});byId('report').value=data.report;await copyValue('report');byId('reportDetails').open=false;document.querySelectorAll('[data-provider]').forEach(button=>button.disabled=false);feedback('reportResult','Richiesta preparata e copiata. Apri la tua AI e incollala nella chat.','ok')},'reportResult').catch(()=>{})}
async function copyReport(){try{await copyValue('report');feedback('reportResult','Richiesta copiata negli appunti.','ok')}catch(error){feedback('reportResult',error.message,'error')}}
async function openProvider(url){if(!byId('report').value){feedback('reportResult','Prepara prima la richiesta.','error');return}const opened=window.open(url,'_blank','noopener');try{await copyValue('report');feedback('reportResult',opened?'Richiesta copiata. Incollala nella chat appena aperta.':'Richiesta copiata. Il browser ha bloccato la nuova scheda: apri manualmente la tua AI.','ok')}catch(error){feedback('reportResult',error.message,'error')}}
async function pasteInto(id,resultId){try{byId(id).value=await navigator.clipboard.readText();feedback(resultId,'Testo incollato dagli appunti.','ok')}catch(_){feedback(resultId,'Il browser non consente l’incolla automatico: tieni premuto nel campo e scegli Incolla.','error')}}
async function downloadArtifact(id,filename){const response=await fetch('/api/artifacts/'+encodeURIComponent(id),{headers:headers()});if(!response.ok)throw new Error((await response.json()).error||'Download fallito');const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=filename||'download.bin';document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}
async function exportFiles(){await withBusy(async()=>{const text=byId('downloadRequest').value;if(!text.includes('#scarica'))throw new Error('Incolla la risposta che contiene la riga #scarica.');const data=await api('/api/export',{text});await downloadArtifact(data.artifact_id,data.filename);feedback('exportResult',`ZIP pronto: ${data.files.length} file richiesti. Allegalo alla chat dell’AI.`,'ok')},'exportResult').catch(()=>{})}

function resetPlan(){currentChanges=[];byId('preview').className='preview';byId('applyButton').disabled=true;byId('diff').textContent='';byId('changeList').replaceChildren()}
function showPlan(data){currentPlanId=data.plan_id;currentChanges=data.changes||[];byId('preview').className='preview visible';byId('applyButton').disabled=false;byId('diff').textContent=data.diff||'Nessuna differenza testuale disponibile.';const list=byId('changeList');list.replaceChildren();currentChanges.forEach(change=>{const item=document.createElement('li');item.textContent=`${change.kind}: ${change.target}`;list.appendChild(item)});const warning=(data.warnings||[]).length?` Avvisi: ${data.warnings.join(' · ')}`:'';feedback('planSummary',`${currentChanges.length} file pronti per la revisione.${warning}`,'ok');byId('preview').scrollIntoView({behavior:'smooth',block:'start'})}
async function uploadZip(){await withBusy(async()=>{const file=byId('zipFile').files[0];if(!file)throw new Error('Seleziona lo ZIP restituito dall’AI.');const response=await fetch('/api/zip/upload',{method:'POST',headers:headers({'Content-Type':'application/zip','X-File-Name':encodeURIComponent(file.name),'X-Local-Bridge-CSRF':csrf}),body:await file.arrayBuffer()});showPlan(await jsonResponse(response))},'planSummary').catch(()=>{})}
async function inspectPatch(){await withBusy(async()=>{const text=byId('patchText').value.trim();if(!text)throw new Error('Incolla prima la risposta SEARCH/REPLACE.');showPlan(await api('/api/patch/inspect',{text}))},'planSummary').catch(()=>{})}
async function applyPlan(){if(!currentPlanId||!confirm(`Applicare ${currentChanges.length} file al progetto? Verrà creato un backup.`))return;await withBusy(async()=>{const data=await api('/api/plan/apply',{plan_id:currentPlanId,confirm:'APPLY'});currentPlanId=null;byId('applyButton').disabled=true;feedback('applyResult','Aggiornamento applicato. Ora puoi eseguire i test di verifica.','ok');byId('verificationTools').open=true;return data},'applyResult').catch(()=>{})}
async function rollback(){if(!confirm('Ripristinare l’ultimo aggiornamento applicato?'))return;await withBusy(async()=>{await api('/api/rollback',{confirm:'ROLLBACK'});feedback('toolResult','Rollback completato.','ok')},'toolResult').catch(()=>{})}
async function runTool(path,label){await withBusy(async()=>{const data=await api(path,{});feedback('toolResult',data.output||label,'ok')},'toolResult').catch(()=>{})}
async function restartProgram(){if(!confirm('Riavviare BridgAI?'))return;await withBusy(async()=>{await api('/api/restart',{});feedback('toolResult','Riavvio richiesto. La pagina verrà ricaricata.','ok');setTimeout(()=>window.location.reload(),4000)},'toolResult').catch(()=>{})}
refreshStatus();
"""
